### ISSUE TITLE
Unable to remove middleware

### ISSUE THREAD

**Issue by mircoservices** [olalonde/connectr#9]
Hi, I was just playing around with connectr, great Work! 

I had a minor issue with removing middleware by name, the call always failed with: 
`Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined` in [connectr/index.js:145](https://github.com/olalonde/connectr/blob/master/index.js#L145). 

I was able to fix this by changing [connectr/index.js:134](https://github.com/olalonde/connectr/blob/master/index.js#L134) to

```
this.stack = stack(this);
order_stack(this.stack);
```

**Comment by faceleg** [comment]
PR?

**Comment by olalonde** [comment]
@faceleg thanks. I haven't used this module in a while, not sure how to fix it :P

**Comment by faceleg** [comment]
Neither, I meant to encourage @mirco312312 to submit a PR, as it appears he is using it

**Comment by shauntarves** [comment]
I think this is a larger issue where the stack wasn't being created from the right attribute. I've submitted a PR here: https://github.com/olalonde/connectr/pull/11
